name: Build and publish installer artifacts for all platforms

on:
  push:
    branches:
      - '0.5'
      - 'Privacy'

env:
 GH_TOKEN: ${{ secrets.GH_RELEASE_DEPLOYMENT_TOKEN }}
 CSC_IDENTITY_AUTO_DISCOVERY: false

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: read version from package.json
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: remove old draft releases
      run: gh release list | grep -e "Draft.*v${{ steps.package-version.outputs.current-version }}" | awk '{print $3}' | xargs -r gh release delete
    - name: create new draft release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GH_RELEASE_DEPLOYMENT_TOKEN }}
        automatic_release_tag: v${{ steps.package-version.outputs.current-version }}
        prerelease: false
        draft: true
        title: ${{ steps.package-version.outputs.current-version }}

  build_release:
    needs: [create_draft_release]
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: 'npm'
      - name: install Linux dev tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libudev-dev
      - name: create NPM config file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ./.npmrc
      - run: npm run setup
      - name: install dmg-license
        if: matrix.os == 'macos-latest'
        run: npm i dmg-license
      - run: npm run compile
      - run: npm run test:unit:main -- --testTimeout=1000 --verbose
      - run: npm run test:unit:components
      - run: npm run bundle
      - name: Sleep for 4 seconds
        shell: bash
        run: sleep 4
      - run: npm run publish
